import Link from "next/link";
import { ArrowUpRight, ArrowDown } from "lucide-react";
import { designs, imageUrl, caseStudy } from "@/data/projects";

const links={behance:"https://www.behance.net/fahimmuddasir",facebook:"https://www.facebook.com/syedfahim.muddasir/",instagram:"https://instagram.com/mr_relax_bro",github:"https://github.com/Fahim-hash",whatsapp:"https://wa.me/8801855941177"};
const clientLogos=[
  ["TongErKhobor","https://www.instagram.com/tongerkhobor","tongerkhobor.png"],["General Science Olympiad","https://www.facebook.com/generalscienceolympiad","sciencebaze.png"],["Ta'atuf Foundation","https://www.facebook.com/taatuf.foundation","taatuf.png"],["Willes Literary Club","https://www.wlc.pro.bd","vb.png"],["RelaxStudio","https://www.instagram.com/relaxstudio__","relax.png"],["Omni Diplomatic Forum","https://www.facebook.com/OMNIDF","odf.png"]
];
const rawLogo=(file:string)=>`https://raw.githubusercontent.com/Fahim-hash/portfolio/main/public/logos/${file}`;

export default function Home(){return <main><div className="wrap">
<nav className="nav"><Link className="brand" href="/">FAHIM<span>.</span></Link><div className="navlinks"><Link href="/work">Work</Link><Link href="/about">About</Link><Link href="/services">Services</Link><Link href="/archive">Archive</Link></div><a className="pill" href={links.whatsapp}>LET&apos;S TALK ↗</a></nav>
<section className="hero" id="top"><div className="eyebrow mono">Graphic designer / Creative technologist / Dhaka</div><h1>I MAKE<br/><em>IDEAS</em> LOOK<br/>IMPOSSIBLE<br/>TO IGNORE.</h1><div className="hero-bottom"><p className="intro">I&apos;m Fahim — a multidisciplinary designer building identities, campaigns and digital experiences with strategy, curiosity and obsessive attention to detail.</p><Link className="scroll mono" href="/work">Explore the work <ArrowDown size={14}/></Link></div></section>
<section id="work" className="section"><div className="section-head"><h2>Selected designs</h2><Link className="mono" href="/work">10 works ↗</Link></div><div className="projects">{designs.slice(0,6).map(d=><Link className="project" href="/work" key={d.slug}><div className="visual"><img src={imageUrl(d.image)} alt={`${d.client} — ${d.title}`}/><span className="mono project-index">{d.number} / {d.year}</span><span className="view">OPEN WORK ↗</span></div><div className="project-info"><span className="project-title">{d.title}</span><span className="project-meta">{d.client}</span></div></Link>)}</div></section>
<section className="section featured"><div className="section-head"><h2>One real case study</h2><span className="mono">The only detailed case study in the original portfolio</span></div><div className="featured-grid"><div className="featured-image"><img src={imageUrl("work5.png")} alt={caseStudy.title}/></div><div className="featured-copy"><span className="eyebrow mono">{caseStudy.year} / {caseStudy.category}</span><h2>{caseStudy.title}</h2><p>{caseStudy.description}</p><div className="case-actions"><Link className="pill" href="/case-study">Open case study ↗</Link><a className="pill" href={caseStudy.external} target="_blank" rel="noreferrer">Behance ↗</a></div></div></div></section>
<section className="section archive-strip"><div><span className="eyebrow mono">Original portfolio assets</span><h2>Real work.<br/><i>No invented projects.</i></h2></div><Link className="pill" href="/archive">Open visual archive ↗</Link></section>
<section id="about" className="section"><div className="section-head"><h2>About</h2><Link className="mono" href="/about">Full profile ↗</Link></div><div className="about-grid"><p className="big-copy">Based in Dhaka, I specialize in crafting cinematic visual identities, advanced photo manipulation, and automated digital tools that bridge aesthetics with function.</p><div className="details"><div className="detail"><h3>Creative expertise</h3><p>Visual Branding · Logo Design · Social Media Poster Design · Event Branding · T-Shirt Design · Motion Graphics · Video Editing · Photography</p></div><div className="detail"><h3>Experience</h3><p>2yr+ creative expertise in the original portfolio.</p></div><div className="detail"><h3>Based in</h3><p>Dhaka, Bangladesh<br/>Available worldwide<br/>Remote / Hybrid / On-site</p></div><div className="detail"><h3>Founder</h3><p>RelaxStudio — with work across TongErKhobor, Willes Literary Club, Ta&apos;atuf Foundation and Omni Diplomatic Forum.</p></div></div></div></section>
<section id="clients" className="section"><div className="section-head"><h2>Working with</h2><span className="mono">From the original portfolio</span></div><div className="client-grid">{clientLogos.map(([name,url,img])=><a className="client" href={url} target="_blank" rel="noreferrer" key={name}><img src={rawLogo(img)} alt={name}/><span>{name}</span><ArrowUpRight size={16}/></a>)}</div></section>
<section id="services" className="section"><div className="section-head"><h2>What I do</h2><Link className="mono" href="/services">Capabilities ↗</Link></div><div className="services">{[["01","Visual branding","Logo Design · Brand systems · Identity"],["02","Social & event design","Posters · Campaigns · Event branding"],["03","Motion & video","Motion graphics · Video editing"],["04","Digital & creative tech","UI/UX · Digital tools · Automation"]].map(x=><Link className="service" href="/services" key={x[0]}><span className="service-num">{x[0]}</span><h3>{x[1]}</h3><span>{x[2]}</span><ArrowUpRight size={18}/></Link>)}</div></section>
</div><section id="contact" className="contact"><div className="wrap"><div className="eyebrow mono">Have a project in mind?</div><h2>LET&apos;S MAKE<br/>SOMETHING <span>WORTH<br/>TALKING ABOUT.</span></h2><div className="contact-row"><a className="email" href="mailto:fahimnafiz70@gmail.com">fahimnafiz70@gmail.com ↗</a><div className="socials"><a href={links.behance}>BEHANCE ↗</a><a href={links.instagram}>INSTAGRAM ↗</a><a href={links.facebook}>FACEBOOK ↗</a><a href={links.github}>GITHUB ↗</a></div></div></div></section><div className="wrap footer"><span>© 2026 SYED FAHIM MUDDASIR</span><span>BUILT WITH NEXT.JS & FRAMER MOTION.</span></div></main>}
