import { ArrowUpRight, ArrowDown } from "lucide-react";

const images = ["Artboard%201.png","banner.png","eid.png","work1.png","work10.png","work2.jpg","work2.png","work3.png","work5.png","work7.png","work8.png"];
const projects = [
  ["01","NEXORA","Brand Identity · Art Direction","2025","work1.png"],
  ["02","AAROH","Identity · Digital Experience","2025","banner.png"],
  ["03","AKSARA","Editorial · Visual System","2024","work2.png"],
  ["04","ORION","Campaign · Social Design","2024","work3.png"],
  ["05","WIDE","Creative Direction · Digital","2024","work5.png"],
  ["06","EVERGLOW GEMS","E-commerce · Product Design","2024","work7.png"],
  ["07","WILLIANS STUDY TOUR 26","Event Branding · Campaign","2026","banner.png"],
  ["08","MADE SIHO","Social · Visual Direction","2025","work8.png"],
];
const raw=(file:string)=>`https://raw.githubusercontent.com/Fahim-hash/portfolio/main/public/designs/${file}`;
const links={behance:"https://www.behance.net/fahimmuddasir",facebook:"https://www.facebook.com/syedfahim.muddasir/",instagram:"https://instagram.com/mr_relax_bro",github:"https://github.com/Fahim-hash",whatsapp:"https://wa.me/8801855941177"};

export default function Home(){return <main><div className="wrap">
<nav className="nav"><a className="brand" href="/">FAHIM<span>.</span></a><div className="navlinks"><a href="/work">Work</a><a href="/about">About</a><a href="/services">Services</a><a href="/archive">Archive</a></div><a className="pill" href={links.whatsapp}>LET&apos;S TALK ↗</a></nav>
<section className="hero" id="top"><div className="eyebrow mono">Graphic designer / Creative technologist / Dhaka</div><h1>I MAKE<br/><em>IDEAS</em> LOOK<br/>IMPOSSIBLE<br/>TO IGNORE.</h1><div className="hero-bottom"><p className="intro">I&apos;m Fahim — a multidisciplinary designer building identities, campaigns and digital experiences with strategy, curiosity and obsessive attention to detail.</p><a className="scroll mono" href="/work">Explore the work <ArrowDown size={14}/></a></div></section>
<section id="work" className="section"><div className="section-head"><h2>Selected work</h2><a className="mono" href="/work">08 projects ↗</a></div><div className="projects">{projects.map(([n,title,meta,year,img])=><a className="project" href={`/work/${title.toLowerCase().replaceAll(" ","-")}`} key={title}><div className="visual"><img src={raw(img)} alt={title}/><span className="mono project-index">{n} / {year}</span><span className="view">VIEW CASE STUDY ↗</span></div><div className="project-info"><span className="project-title">{title}</span><span className="project-meta">{meta}</span></div></a>)}</div></section>
<section className="section archive-strip"><div><span className="eyebrow mono">Real assets from the original portfolio</span><h2>Nothing replaced.<br/><i>Everything resurfaced.</i></h2></div><a className="pill" href="/archive">Open visual archive ↗</a></section>
<section id="about" className="section"><div className="section-head"><h2>About</h2><a className="mono" href="/about">Full story ↗</a></div><div className="about-grid"><p className="big-copy">Design is not decoration. It&apos;s the moment an idea becomes <i>felt.</i> I turn messy problems into clear visual stories people remember.</p><div className="details"><div className="detail"><h3>Approach</h3><p>Research first. Find the sharpest idea. Build a visual language that feels inevitable.</p></div><div className="detail"><h3>Currently</h3><p>Exploring graphic design, creative coding, digital products, motion and culture.</p></div><div className="detail"><h3>Based in</h3><p>Dhaka, Bangladesh<br/>Available worldwide<br/>Remote / Hybrid / On-site</p></div><div className="detail"><h3>Outside the screen</h3><p>Music, cinema, typography, street culture and collecting references that become projects.</p></div></div></div></section>
<section id="services" className="section"><div className="section-head"><h2>What I do</h2><a className="mono" href="/services">Capabilities ↗</a></div><div className="services">{[["01","Brand identity","Strategy · Naming · Visual systems"],["02","Art direction","Campaigns · Editorial · Social"],["03","Digital design","Web · UI · Product experiences"],["04","Creative technology","Interactive · Motion · Experiments"]].map(x=><a className="service" href="/services" key={x[0]}><span className="service-num">{x[0]}</span><h3>{x[1]}</h3><span>{x[2]}</span><ArrowUpRight size={18}/></a>)}</div></section>
</div><section id="contact" className="contact"><div className="wrap"><div className="eyebrow mono">Have a project in mind?</div><h2>LET&apos;S MAKE<br/>SOMETHING <span>WORTH<br/>TALKING ABOUT.</span></h2><div className="contact-row"><a className="email" href={links.whatsapp}>WhatsApp ↗</a><div className="socials"><a href={links.behance}>BEHANCE ↗</a><a href={links.instagram}>INSTAGRAM ↗</a><a href={links.facebook}>FACEBOOK ↗</a><a href={links.github}>GITHUB ↗</a></div></div></div></section><div className="wrap footer"><span>© 2026 FAHIM / ALL RIGHTS RESERVED</span><span>DESIGNED & BUILT WITH INTENT.</span></div></main>}
