import Link from "next/link";
import { ArrowDown, ArrowUpRight, MoveUpRight } from "lucide-react";
import { designs, imageUrl, caseStudy } from "@/data/projects";

const links={behance:"https://www.behance.net/fahimmuddasir",facebook:"https://www.facebook.com/syedfahim.muddasir/",instagram:"https://instagram.com/mr_relax_bro",github:"https://github.com/Fahim-hash",whatsapp:"https://wa.me/8801855941177"};
const clientLogos=[["TongErKhobor","https://www.instagram.com/tongerkhobor","tongerkhobor.png"],["General Science Olympiad","https://www.facebook.com/generalscienceolympiad","sciencebaze.png"],["Ta'atuf Foundation","https://www.facebook.com/taatuf.foundation","taatuf.png"],["Willes Literary Club","https://www.wlc.pro.bd","vb.png"],["RelaxStudio","https://www.instagram.com/relaxstudio__","relax.png"],["Omni Diplomatic Forum","https://www.facebook.com/OMNIDF","odf.png"]];
const rawLogo=(file:string)=>`https://raw.githubusercontent.com/Fahim-hash/portfolio/main/public/logos/${file}`;

export default function Home(){return <main><div className="noise" aria-hidden="true"/><div className="wrap">
<nav className="nav"><Link className="brand" href="/">FAHIM<span>®</span></Link><div className="nav-center"><Link href="/work">Work</Link><Link href="/about">About</Link><Link href="/services">Services</Link></div><div className="nav-right"><span className="status"><i/> Available for work</span><a className="nav-cta" href={links.whatsapp}>Let&apos;s talk <ArrowUpRight size={14}/></a></div></nav>
<section className="hero" id="top"><div className="hero-topline"><span>Independent designer &amp; creative technologist</span><span className="mono">Dhaka — Bangladesh / 2026</span></div><div className="hero-title-wrap"><p className="hero-kicker mono">Visual identity · Campaign · Digital</p><h1>MAKE IT<br/><span>MATTER.</span></h1><div className="hero-stamp"><span>F</span><small>SYED FAHIM<br/>MUDDASIR</small></div></div><div className="hero-bottom"><p className="hero-intro">Based in Dhaka, I specialize in crafting cinematic visual identities, advanced photo manipulation, and automated digital tools that bridge aesthetics with function.</p><Link className="hero-link" href="/work"><span>Scroll to explore</span><ArrowDown size={17}/></Link></div></section>
<section className="marquee" aria-label="Capabilities"><div className="marquee-track">VISUAL BRANDING <b>✳</b> ART DIRECTION <b>✳</b> SOCIAL DESIGN <b>✳</b> EVENT BRANDING <b>✳</b> MOTION <b>✳</b> CREATIVE TECHNOLOGY <b>✳</b></div></section>
<section className="section work-section" id="work"><div className="section-label"><span>01 / Selected work</span><Link href="/work">View all 10 works <ArrowUpRight size={14}/></Link></div><div className="work-intro"><h2>A selection of<br/><i>real work.</i></h2><p>Designs from the original portfolio — presented as a visual body of work, not fabricated case studies.</p></div><div className="projects editorial-grid">{designs.slice(0,6).map((d,i)=><Link className={`project project-${i+1}`} href="/work" key={d.slug}><div className="visual"><img src={imageUrl(d.image)} alt={`${d.client} — ${d.title}`}/><span className="project-no mono">{String(d.number).padStart(2,"0")}</span><span className="project-open">Open ↗</span></div><div className="project-info"><div><strong>{d.title}</strong><span>{d.client}</span></div><span className="mono">{d.year}</span></div></Link>)}</div></section>
<section className="case-section"><div className="section-label"><span>02 / Featured case study</span><span className="mono">Only detailed case study</span></div><div className="case-layout"><div className="case-image"><img src={imageUrl("work5.png")} alt={caseStudy.title}/><span className="case-tag">360° EVENT BRANDING</span></div><div className="case-copy"><span className="mono case-year">{caseStudy.year} / {caseStudy.category}</span><h2>{caseStudy.title}</h2><p>{caseStudy.description}</p><Link className="dark-button" href="/case-study">Read the case study <ArrowUpRight size={16}/></Link></div></div></section>
<section className="section clients-section"><div className="section-label"><span>03 / Selected clients</span><span>From the original portfolio</span></div><div className="client-grid">{clientLogos.map(([name,url,img],i)=><a className="client" href={url} target="_blank" rel="noreferrer" key={name}><span className="mono">0{i+1}</span><img src={rawLogo(img)} alt={name}/><strong>{name}</strong><ArrowUpRight size={16}/></a>)}</div></section>
<section className="section about-teaser"><div className="section-label"><span>04 / About</span><Link href="/about">Full profile <ArrowUpRight size={14}/></Link></div><div className="about-teaser-grid"><h2>Design with<br/><i>intention.</i></h2><div><p>2yr+ creative expertise across visual branding, logo design, social media poster design, event branding, T-shirt design, motion graphics, video editing and photography.</p><Link className="text-link" href="/about">More about Fahim <ArrowUpRight size={15}/></Link></div></div></section>
<section className="section services-teaser"><div className="section-label"><span>05 / Capabilities</span><Link href="/services">All services <ArrowUpRight size={14}/></Link></div><div className="service-list">{[["01","Visual branding","Logo Design · Brand systems · Identity"],["02","Social & event design","Posters · Campaigns · Event branding"],["03","Motion & video","Motion graphics · Video editing"],["04","Digital & creative tech","UI/UX · Digital tools · Automation"]].map(([n,title,desc])=><Link className="service" href="/services" key={n}><span className="mono">{n}</span><h3>{title}</h3><span className="service-desc">{desc}</span><MoveUpRight size={18}/></Link>)}</div></section>
</div><section className="contact" id="contact"><div className="wrap"><span className="mono contact-kicker">06 / Start a conversation</span><h2>HAVE AN IDEA?<br/><i>LET&apos;S MAKE IT REAL.</i></h2><div className="contact-bottom"><a className="contact-email" href="mailto:fahimnafiz70@gmail.com">fahimnafiz70@gmail.com <ArrowUpRight size={20}/></a><div className="socials"><a href={links.behance}>Behance ↗</a><a href={links.instagram}>Instagram ↗</a><a href={links.facebook}>Facebook ↗</a><a href={links.github}>GitHub ↗</a></div></div></div></section><footer className="wrap footer"><span>© 2026 Syed Fahim Muddasir</span><span>Dhaka, Bangladesh</span><span>Independent designer / creative technologist</span></footer></main>}
